// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicaOdontologica.API.Migrations
{
    [DbContext(typeof(ClinicaOdontologicaAPIContext))]
    [Migration("20260925020918_V01")]
    partial class V01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicaOdontologicaModelos.Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCita"));

                    b.Property<string>("EstadoCita")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_cita");

                    b.Property<TimeOnly>("FechaCita")
                        .HasColumnType("time without time zone")
                        .HasColumnName("fecha_cita");

                    b.Property<int>("IdConsultorio")
                        .HasColumnType("integer")
                        .HasColumnName("id_consultorio");

                    b.Property<int>("IdOdontologo")
                        .HasColumnType("integer")
                        .HasColumnName("id_odontologo");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.HasKey("IdCita");

                    b.HasIndex("IdConsultorio");

                    b.HasIndex("IdOdontologo");

                    b.HasIndex("IdPaciente");

                    b.ToTable("citas");
                });

            modelBuilder.Entity("ClinicaOdontologicaModelos.Consultorio", b =>
                {
                    b.Property<int>("IdConsultorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_consultorio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConsultorio"));

                    b.Property<string>("EquipamientoPrincipal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("equipamiento_principal");

                    b.Property<string>("NumeroSala")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_sala");

                    b.Property<int>("Piso")
                        .HasColumnType("integer")
                        .HasColumnName("piso");

                    b.HasKey("IdConsultorio");

                    b.ToTable("Consultorios");
                });

            modelBuilder.Entity("ClinicaOdontologicaModelos.DetalleCita", b =>
                {
                    b.Property<int>("IdDetalleCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_cita");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalleCita"));

                    b.Property<decimal>("CostoAplicado")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_aplicado");

                    b.Property<int>("IdCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdDetalleCita");

                    b.HasIndex("IdCita");

                    b.ToTable("DetalleCitas");
                });

            modelBuilder.Entity("ClinicaOdontologicaModelos.Especialidad", b =>
                {
                    b.Property<int>("IdEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEspecialidad"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombreEspecialidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_especialidad");

                    b.HasKey("IdEspecialidad");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("ClinicaOdontologicaModelos.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_factura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFactura"));

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_pago");

                    b.Property<DateTime>("FechaFactura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("IdCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("impuesto");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdCita");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("ClinicaOdontologicaModelos.HistorialMedico", b =>
                {
                    b.Property<int>("IdHistorialMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_historial_medico");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHistorialMedico"));

                    b.Property<string>("Alergias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alergias");

                    b.Property<string>("Enfermedades")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("enfermedades");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<string>("TipoSangre")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("tipo_sangre");

                    b.HasKey("IdHistorialMedico");

                    b.HasIndex("IdPaciente")
                        .IsUnique();

                    b.ToTable("HistorialesMedicos");
                });

            modelBuilder.Entity("ClinicaOdontologicaModelos.Odontologo", b =>
                {
                    b.Property<int>("IdOdontologo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_odontologo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOdontologo"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellidos");

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidad");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombres");

                    b.Property<string>("RegistroMedico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("registro_medico");

                    b.HasKey("IdOdontologo");

                    b.HasIndex("IdEspecialidad");

                    b.ToTable("Odontologos");
                });

            modelBuilder.Entity("ClinicaOdontologicaModelos.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("telefono");

                    b.HasKey("IdPaciente");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ClinicaOdontologicaModelos.Receta", b =>
                {
                    b.Property<int>("IdReceta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_receta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReceta"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("date")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("IdCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<string>("Indicaciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("indicaciones");

                    b.HasKey("IdReceta");

                    b.HasIndex("IdCita");

                    b.ToTable("Recetas");
                });

            modelBuilder.Entity("ClinicaOdontologicaModelos.Tratamiento", b =>
                {
                    b.Property<int>("IdTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdTratamiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTratamiento"));

                    b.Property<decimal>("costoBase")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costoBase");

                    b.Property<int>("duracionMin")
                        .HasColumnType("integer")
                        .HasColumnName("duracionMin");

                    b.Property<string>("nombreTratamiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombreTratamiento");

                    b.HasKey("IdTratamiento");

                    b.ToTable("Tratamientos");
                });

            modelBuilder.Entity("ClinicaOdontologicaModelos.Cita", b =>
                {
                    b.HasOne("ClinicaOdontologicaModelos.Consultorio", "consultorio")
                        .WithMany()
                        .HasForeignKey("IdConsultorio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologicaModelos.Odontologo", "odontologo")
                        .WithMany()
                        .HasForeignKey("IdOdontologo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologicaModelos.Paciente", "paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("consultorio");

                    b.Navigation("odontologo");

                    b.Navigation("paciente");
                });

            modelBuilder.Entity("ClinicaOdontologicaModelos.DetalleCita", b =>
                {
                    b.HasOne("ClinicaOdontologicaModelos.Cita", "cita")
                        .WithMany()
                        .HasForeignKey("IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cita");
                });

            modelBuilder.Entity("ClinicaOdontologicaModelos.Factura", b =>
                {
                    b.HasOne("ClinicaOdontologicaModelos.Cita", "cita")
                        .WithMany()
                        .HasForeignKey("IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cita");
                });

            modelBuilder.Entity("ClinicaOdontologicaModelos.HistorialMedico", b =>
                {
                    b.HasOne("ClinicaOdontologicaModelos.Paciente", "paciente")
                        .WithOne("HistorialMedico")
                        .HasForeignKey("ClinicaOdontologicaModelos.HistorialMedico", "IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("paciente");
                });

            modelBuilder.Entity("ClinicaOdontologicaModelos.Odontologo", b =>
                {
                    b.HasOne("ClinicaOdontologicaModelos.Especialidad", "especialidad")
                        .WithMany()
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("especialidad");
                });

            modelBuilder.Entity("ClinicaOdontologicaModelos.Receta", b =>
                {
                    b.HasOne("ClinicaOdontologicaModelos.Cita", "cita")
                        .WithMany()
                        .HasForeignKey("IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cita");
                });

            modelBuilder.Entity("ClinicaOdontologicaModelos.Paciente", b =>
                {
                    b.Navigation("HistorialMedico");
                });
#pragma warning restore 612, 618
        }
    }
}
